version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.39.0-focal  
    environment:
      CIRCLE_REPOSITORY_URL: git@github.com:shashank-maker-co/demo-test.git
      CHECKLY_API_KEY: cu_859b0d3e81c442969a39940978cf3a57
      CHECKLY_ACCOUNT_ID: f45eb769-ac48-4fc4-bd66-e74f991861bf
    working_directory: ~/demo-test
    steps:
      - run:
          name: "Clone test repository"
          command: | 
            git clone --branch main https://github.com/makerinc/checks-playwright-pages.git
      - run:
          name: "DOWNLOAD DEPENDENCIES"
          environment:
            SECRET_KEY: SECRET_KEY 
          command: cd demo-test && npm ci
      - run:
          name: "RUN CHECKLY TESTS"
          command: cd demo-test && npx checkly test --record
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build