version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying code using https://github.com/shashank-maker-co/demo-dev"
  test:
    executor: node/default
    steps:
      - checkout:
          git:
            url: https://github.com/shashank-maker-co/demo-test.git
            ref: main
          path: ~/demo-test
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Run tests"
          command: npx playwright test

workflows:
  deploy-and-test:
    jobs:
      - deploy
      - test:
          requires:
            - deploy