version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  say-hello:
    executor: node/default 
    working_directory: ~/repo
    steps:
      - checkout
      - node/install: 
          node-version: "14.17.6"
      - run:
          name: "Run node app"
          command: |
            npm install
            PORT=$(shuf -i 8081-65535 -n 1)
            echo "Starting server on port $PORT"
            node app --port $PORT
          environment:
            PORT: 8080
      - run:
          name: "Stop web server"
          command: "sleep 2m && kill $(lsof -t -i:$PORT) || true"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello