version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    environment:
      CIRCLE_REPOSITORY_URL: git@github.com:shashank-maker-co/demo-test.git
    steps:
      - node/install:
          node-version: "14.17.6"
      - run:
          name: Clone test repository
          command: | 
            git clone --branch main https://github.com/shashank-maker-co/demo-test.git
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Run tests"
          command: npx playwright test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build