version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/node:20.8.0
    environment:
      CIRCLE_REPOSITORY_URL: git@github.com:shashank-maker-co/demo-test.git
    working_directory: ~/demo-test
    steps:
      - run:
          name: "Clone test repository"
          command: | 
            git clone --branch main https://github.com/shashank-maker-co/demo-test.git
      - run:
          name: "Install dependencies"
          command: cd demo-test && npm install
      - run:
          name: "Install Playwright Browsers Deps"
          command: cd demo-test && sudo npx playwright install-deps     
      - run:
          name: "Install Playwright"
          command: cd demo-test && npx playwright install
      - run:
          name: "Run tests"
          command: cd demo-test && npx playwright test --output=results
      - store_test_results:
          path: demo-test/results
      - run:
          name: List directory content
          command: ls -R
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build