version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  say-hello:
    executor: node/default 
    working_directory: ~/repo
    steps:
      - checkout
      - node/install: 
          node-version: "14.17.6"
      - run:
          name: "Run node app"
          command: "npm install && node app"
      - store_artifacts:
          path: dist
workflows:
  say-hello-workflow:
    jobs:
      - say-hello