version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: circleci/node:14
    environment:
      CIRCLE_REPOSITORY_URL: git@github.com:shashank-maker-co/demo-test.git
    working_directory: ~/demo-test
    steps:
       - run:
          name: Clone test repository
          command: | 
            git clone --branch main https://github.com/shashank-maker-co/demo-test.git
      - run:
          name: "Install dependencies"
          command: cd demo-test && npm install
      - run:
          name: "Run tests"
          command: npx playwright test
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build