version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    steps:
      - run:
          name: "Clone test repository"
          command: | 
            git clone --branch main https://github.com/shashank-maker-co/demo-test.git
      - run:
          name: Download dependency
          environment:
            SECRET_KEY: SECRET_KEY 
          command: npm ci
      - run:
          name: "Run tests"
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: test-results
      - run:
          name: "Print working directory"
          command: pwd
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build