version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  run-node-app:
    parameters:
      port:
        type: integer # specify the type of the parameter
        default: 3000 # specify the default value of the parameter
    steps:
      - node/install
      - run:
          name: "Run node app"
          command: "npm install && node app"
          environment:
            PORT: << parameters.port >> # use the parameter value for PORT

jobs:
  say-hello:
    executor: node/default