version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run node app"
          command: "npm install && node app"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello